// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: check_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RightsCheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemoteApps []*APP `protobuf:"bytes,1,rep,name=remote_apps,json=remoteApps,proto3" json:"remote_apps,omitempty"`
}

func (x *RightsCheckRequest) Reset() {
	*x = RightsCheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_check_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RightsCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RightsCheckRequest) ProtoMessage() {}

func (x *RightsCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_check_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RightsCheckRequest.ProtoReflect.Descriptor instead.
func (*RightsCheckRequest) Descriptor() ([]byte, []int) {
	return file_check_message_proto_rawDescGZIP(), []int{0}
}

func (x *RightsCheckRequest) GetRemoteApps() []*APP {
	if x != nil {
		return x.RemoteApps
	}
	return nil
}

type RightsCheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Apps []*AppRightsInfo `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
}

func (x *RightsCheckResponse) Reset() {
	*x = RightsCheckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_check_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RightsCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RightsCheckResponse) ProtoMessage() {}

func (x *RightsCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_check_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RightsCheckResponse.ProtoReflect.Descriptor instead.
func (*RightsCheckResponse) Descriptor() ([]byte, []int) {
	return file_check_message_proto_rawDescGZIP(), []int{1}
}

func (x *RightsCheckResponse) GetApps() []*AppRightsInfo {
	if x != nil {
		return x.Apps
	}
	return nil
}

type AppRightsInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemoteApp *APP `protobuf:"bytes,1,opt,name=remote_app,json=remoteApp,proto3" json:"remote_app,omitempty"`
	HasRights bool `protobuf:"varint,2,opt,name=has_rights,json=hasRights,proto3" json:"has_rights,omitempty"`
}

func (x *AppRightsInfo) Reset() {
	*x = AppRightsInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_check_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppRightsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppRightsInfo) ProtoMessage() {}

func (x *AppRightsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_check_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppRightsInfo.ProtoReflect.Descriptor instead.
func (*AppRightsInfo) Descriptor() ([]byte, []int) {
	return file_check_message_proto_rawDescGZIP(), []int{2}
}

func (x *AppRightsInfo) GetRemoteApp() *APP {
	if x != nil {
		return x.RemoteApp
	}
	return nil
}

func (x *AppRightsInfo) GetHasRights() bool {
	if x != nil {
		return x.HasRights
	}
	return false
}

var File_check_message_proto protoreflect.FileDescriptor

var file_check_message_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x61, 0x70, 0x70, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x12, 0x52, 0x69, 0x67, 0x68,
	0x74, 0x73, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25,
	0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x61, 0x70, 0x70, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x41, 0x50, 0x50, 0x52, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x41, 0x70, 0x70, 0x73, 0x22, 0x39, 0x0a, 0x13, 0x52, 0x69, 0x67, 0x68, 0x74, 0x73, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x04,
	0x61, 0x70, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x41, 0x70, 0x70,
	0x52, 0x69, 0x67, 0x68, 0x74, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x61, 0x70, 0x70, 0x73,
	0x22, 0x53, 0x0a, 0x0d, 0x41, 0x70, 0x70, 0x52, 0x69, 0x67, 0x68, 0x74, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x23, 0x0a, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x61, 0x70, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x41, 0x50, 0x50, 0x52, 0x09, 0x72, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x41, 0x70, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x61, 0x73, 0x5f, 0x72, 0x69,
	0x67, 0x68, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x68, 0x61, 0x73, 0x52,
	0x69, 0x67, 0x68, 0x74, 0x73, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_check_message_proto_rawDescOnce sync.Once
	file_check_message_proto_rawDescData = file_check_message_proto_rawDesc
)

func file_check_message_proto_rawDescGZIP() []byte {
	file_check_message_proto_rawDescOnce.Do(func() {
		file_check_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_check_message_proto_rawDescData)
	})
	return file_check_message_proto_rawDescData
}

var file_check_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_check_message_proto_goTypes = []interface{}{
	(*RightsCheckRequest)(nil),  // 0: RightsCheckRequest
	(*RightsCheckResponse)(nil), // 1: RightsCheckResponse
	(*AppRightsInfo)(nil),       // 2: AppRightsInfo
	(*APP)(nil),                 // 3: APP
}
var file_check_message_proto_depIdxs = []int32{
	3, // 0: RightsCheckRequest.remote_apps:type_name -> APP
	2, // 1: RightsCheckResponse.apps:type_name -> AppRightsInfo
	3, // 2: AppRightsInfo.remote_app:type_name -> APP
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_check_message_proto_init() }
func file_check_message_proto_init() {
	if File_check_message_proto != nil {
		return
	}
	file_app_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_check_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RightsCheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_check_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RightsCheckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_check_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppRightsInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_check_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_check_message_proto_goTypes,
		DependencyIndexes: file_check_message_proto_depIdxs,
		MessageInfos:      file_check_message_proto_msgTypes,
	}.Build()
	File_check_message_proto = out.File
	file_check_message_proto_rawDesc = nil
	file_check_message_proto_goTypes = nil
	file_check_message_proto_depIdxs = nil
}
