// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PatchClient is the client API for Patch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PatchClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type patchClient struct {
	cc grpc.ClientConnInterface
}

func NewPatchClient(cc grpc.ClientConnInterface) PatchClient {
	return &patchClient{cc}
}

func (c *patchClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/Patch/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PatchServer is the server API for Patch service.
// All implementations must embed UnimplementedPatchServer
// for forward compatibility
type PatchServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedPatchServer()
}

// UnimplementedPatchServer must be embedded to have forward compatible implementations.
type UnimplementedPatchServer struct {
}

func (UnimplementedPatchServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPatchServer) mustEmbedUnimplementedPatchServer() {}

// UnsafePatchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PatchServer will
// result in compilation errors.
type UnsafePatchServer interface {
	mustEmbedUnimplementedPatchServer()
}

func RegisterPatchServer(s grpc.ServiceRegistrar, srv PatchServer) {
	s.RegisterService(&Patch_ServiceDesc, srv)
}

func _Patch_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatchServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Patch/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatchServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Patch_ServiceDesc is the grpc.ServiceDesc for Patch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Patch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Patch",
	HandlerType: (*PatchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Patch_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "patch_service.proto",
}
