info:
  contact:
    name: PANKAJ KUMAR
  description: Patch APIs helps to describe the available routes for patch master
    server.
  license:
    name: MIT Licence
    url: https://www.github.com/pnkj-kmr/patch/README.md
  title: Patch API
  version: "1.0"
paths:
  /api/check:
    get:
      consumes:
      - application/json
      description: Endpoint check with formal api call
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: status check api call
      tags:
      - Status
  /api/remote/{name}:
    get:
      consumes:
      - application/json
      description: searching remote by name
      parameters:
      - description: Remote Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"ok":"string", "msg": "string", "data": ""}'
          schema:
            type: string
      summary: searching remote by name
      tags:
      - Patch
  /api/remote/{name}/rights:
    get:
      consumes:
      - application/json
      description: getting remote rights of read/write
      parameters:
      - description: Remote Name
        in: path
        name: name
        required: true
        type: string
      - description: Remote Apps
        in: query
        items:
          type: string
        name: apps
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: '{"ok":"string", "msg": "string", "data": ""}'
          schema:
            type: string
      summary: getting remote rights of read/write
      tags:
      - Patch
  /api/remotes:
    get:
      consumes:
      - application/json
      description: getting all remotes
      produces:
      - application/json
      responses:
        "200":
          description: '{"ok":"string", "msg": "string", "data": ""}'
          schema:
            type: string
      summary: getting all available remotes
      tags:
      - Patch
  /api/remotes/rights:
    get:
      consumes:
      - application/json
      description: getting remotes rights of read/write
      produces:
      - application/json
      responses:
        "200":
          description: '{"ok":"string", "msg": "string", "data": ""}'
          schema:
            type: string
      summary: getting remotes rights of read/write
      tags:
      - Patch
swagger: "2.0"
