// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: apply_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Applications []*APP `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
}

func (x *ApplyReq) Reset() {
	*x = ApplyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apply_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyReq) ProtoMessage() {}

func (x *ApplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_apply_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyReq.ProtoReflect.Descriptor instead.
func (*ApplyReq) Descriptor() ([]byte, []int) {
	return file_apply_message_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyReq) GetApplications() []*APP {
	if x != nil {
		return x.Applications
	}
	return nil
}

type ApplyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	App      *APP    `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Verified bool    `protobuf:"varint,2,opt,name=verified,proto3" json:"verified,omitempty"`
	Data     []*FILE `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ApplyInfo) Reset() {
	*x = ApplyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apply_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyInfo) ProtoMessage() {}

func (x *ApplyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_apply_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyInfo.ProtoReflect.Descriptor instead.
func (*ApplyInfo) Descriptor() ([]byte, []int) {
	return file_apply_message_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyInfo) GetApp() *APP {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *ApplyInfo) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *ApplyInfo) GetData() []*FILE {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApplyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Applications []*ApplyInfo `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
}

func (x *ApplyResp) Reset() {
	*x = ApplyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apply_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResp) ProtoMessage() {}

func (x *ApplyResp) ProtoReflect() protoreflect.Message {
	mi := &file_apply_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResp.ProtoReflect.Descriptor instead.
func (*ApplyResp) Descriptor() ([]byte, []int) {
	return file_apply_message_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyResp) GetApplications() []*ApplyInfo {
	if x != nil {
		return x.Applications
	}
	return nil
}

var File_apply_message_proto protoreflect.FileDescriptor

var file_apply_message_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x61, 0x70, 0x70, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x08,
	0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x12, 0x28, 0x0a, 0x0c, 0x61, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x04,
	0x2e, 0x41, 0x50, 0x50, 0x52, 0x0c, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x22, 0x5a, 0x0a, 0x09, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x16, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x41,
	0x50, 0x50, 0x52, 0x03, 0x61, 0x70, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x05, 0x2e, 0x46, 0x49, 0x4c, 0x45, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3b,
	0x0a, 0x09, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x0c, 0x61,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x61,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x2e,
	0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apply_message_proto_rawDescOnce sync.Once
	file_apply_message_proto_rawDescData = file_apply_message_proto_rawDesc
)

func file_apply_message_proto_rawDescGZIP() []byte {
	file_apply_message_proto_rawDescOnce.Do(func() {
		file_apply_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_apply_message_proto_rawDescData)
	})
	return file_apply_message_proto_rawDescData
}

var file_apply_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_apply_message_proto_goTypes = []interface{}{
	(*ApplyReq)(nil),  // 0: ApplyReq
	(*ApplyInfo)(nil), // 1: ApplyInfo
	(*ApplyResp)(nil), // 2: ApplyResp
	(*APP)(nil),       // 3: APP
	(*FILE)(nil),      // 4: FILE
}
var file_apply_message_proto_depIdxs = []int32{
	3, // 0: ApplyReq.applications:type_name -> APP
	3, // 1: ApplyInfo.app:type_name -> APP
	4, // 2: ApplyInfo.data:type_name -> FILE
	1, // 3: ApplyResp.applications:type_name -> ApplyInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_apply_message_proto_init() }
func file_apply_message_proto_init() {
	if File_apply_message_proto != nil {
		return
	}
	file_app_message_proto_init()
	file_file_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_apply_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apply_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apply_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apply_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apply_message_proto_goTypes,
		DependencyIndexes: file_apply_message_proto_depIdxs,
		MessageInfos:      file_apply_message_proto_msgTypes,
	}.Build()
	File_apply_message_proto = out.File
	file_apply_message_proto_rawDesc = nil
	file_apply_message_proto_goTypes = nil
	file_apply_message_proto_depIdxs = nil
}
