// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: extract_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtractReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ExtractReq) Reset() {
	*x = ExtractReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extract_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtractReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractReq) ProtoMessage() {}

func (x *ExtractReq) ProtoReflect() protoreflect.Message {
	mi := &file_extract_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractReq.ProtoReflect.Descriptor instead.
func (*ExtractReq) Descriptor() ([]byte, []int) {
	return file_extract_message_proto_rawDescGZIP(), []int{0}
}

func (x *ExtractReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ExtractReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ExtractResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path     string  `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Verified bool    `protobuf:"varint,2,opt,name=verified,proto3" json:"verified,omitempty"`
	Data     []*FILE `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ExtractResp) Reset() {
	*x = ExtractResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extract_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtractResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractResp) ProtoMessage() {}

func (x *ExtractResp) ProtoReflect() protoreflect.Message {
	mi := &file_extract_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractResp.ProtoReflect.Descriptor instead.
func (*ExtractResp) Descriptor() ([]byte, []int) {
	return file_extract_message_proto_rawDescGZIP(), []int{1}
}

func (x *ExtractResp) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ExtractResp) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *ExtractResp) GetData() []*FILE {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_extract_message_proto protoreflect.FileDescriptor

var file_extract_message_proto_rawDesc = []byte{
	0x0a, 0x15, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x0a, 0x45,
	0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x58, 0x0a, 0x0b, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x12, 0x19, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05,
	0x2e, 0x46, 0x49, 0x4c, 0x45, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x0a, 0x5a, 0x08, 0x2e,
	0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_extract_message_proto_rawDescOnce sync.Once
	file_extract_message_proto_rawDescData = file_extract_message_proto_rawDesc
)

func file_extract_message_proto_rawDescGZIP() []byte {
	file_extract_message_proto_rawDescOnce.Do(func() {
		file_extract_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_extract_message_proto_rawDescData)
	})
	return file_extract_message_proto_rawDescData
}

var file_extract_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_extract_message_proto_goTypes = []interface{}{
	(*ExtractReq)(nil),  // 0: ExtractReq
	(*ExtractResp)(nil), // 1: ExtractResp
	(*FILE)(nil),        // 2: FILE
}
var file_extract_message_proto_depIdxs = []int32{
	2, // 0: ExtractResp.data:type_name -> FILE
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_extract_message_proto_init() }
func file_extract_message_proto_init() {
	if File_extract_message_proto != nil {
		return
	}
	file_file_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_extract_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtractReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extract_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtractResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_extract_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_extract_message_proto_goTypes,
		DependencyIndexes: file_extract_message_proto_depIdxs,
		MessageInfos:      file_extract_message_proto_msgTypes,
	}.Build()
	File_extract_message_proto = out.File
	file_extract_message_proto_rawDesc = nil
	file_extract_message_proto_goTypes = nil
	file_extract_message_proto_depIdxs = nil
}
